apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
patches:
  - path: ingress-nginx-nodeport-patch.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
