namespace: keepstack

image:
  registry: ghcr.io/YOUR_GH_USERNAME_OR_ORG
  tag: "sha-CHANGE-ME"
  pullPolicy: IfNotPresent

secrets:
  create: true
  name: keepstack-secrets
  data:
    DATABASE_URL: "postgres://keepstack:keepstack@keepstack-postgres:5432/keepstack?sslmode=disable"
    NATS_URL: "nats://keepstack-nats:4222"
    JWT_SECRET: "devdevdevdevdevdevdevdevdevdevdevdev"
    SMTP_HOST: "smtp.keepstack.local"
    SMTP_PORT: "587"
    SMTP_USERNAME: "keepstack"
    SMTP_PASSWORD: "changeme"
    DIGEST_SENDER: "Keepstack Digest <digest@keepstack.local>"
    DIGEST_RECIPIENT: "reader@keepstack.local"
    DIGEST_LIMIT: "10"

api:
  replicas: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 6
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi

worker:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

web:
  replicas: 1

digest:
  enabled: true
  schedule: "0 9 * * *"
  limit: 10
  sender: "Keepstack Digest <digest@keepstack.local>"
  recipient: "reader@keepstack.local"

postgres:
  storage: 5Gi
  username: keepstack
  password: keepstack

nats:
  replicas: 1

chrome:
  enabled: true
  replicas: 1

ingress:
  enabled: true
  className: nginx
  host: keepstack.localtest.me
  tls: false
