// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Archive struct {
	LinkID        pgtype.UUID
	Html          pgtype.Text
	ExtractedText pgtype.Text
	WordCount     pgtype.Int4
	Lang          pgtype.Text
}

type Link struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Url       string
	Title     pgtype.Text
	CreatedAt pgtype.Timestamptz
	ReadAt    pgtype.Timestamptz
	Favorite  bool
	SearchTsv interface{}
}

type LinkTag struct {
	LinkID pgtype.UUID
	TagID  int32
}

type Tag struct {
	ID   int32
	Name string
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
