// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Archive struct {
	LinkID        pgtype.UUID
	Html          pgtype.Text
	ExtractedText pgtype.Text
	Title         pgtype.Text
	Byline        pgtype.Text
	Lang          pgtype.Text
	WordCount     pgtype.Int4
}

type Claim struct {
	ID        pgtype.UUID
	LinkID    pgtype.UUID
	UserID    pgtype.UUID
	ClaimedAt pgtype.Timestamptz
}

type Highlight struct {
	ID         pgtype.UUID
	LinkID     pgtype.UUID
	Quote      string
	Annotation pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Link struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Url          string
	Title        pgtype.Text
	CreatedAt    pgtype.Timestamptz
	ReadAt       pgtype.Timestamptz
	Favorite     bool
	SearchTsv    interface{}
	SourceDomain pgtype.Text
}

type LinkTag struct {
	LinkID pgtype.UUID
	TagID  int32
}

type Recommendation struct {
	LinkID    pgtype.UUID
	Score     int32
	UpdatedAt pgtype.Timestamptz
}

type Tag struct {
	ID   int32
	Name string
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
