apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: keepstack
servers: 1
agents: 0
ports:
  - port: 18080:30080
    nodeFilters:
      - loadbalancer
  - port: 18443:30443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
