apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keepstack.fullname" . }}-web
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-web
        app.kubernetes.io/component: web
    spec:
{{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: web
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.webRepository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepstack.fullname" . }}-web
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-web
  ports:
    - name: http
      port: 80
      targetPort: http
