apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keepstack.fullname" . }}-api
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-api
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ include "keepstack.serviceAccountName.api" . }}
      containers:
        - name: api
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.apiRepository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: DATABASE_URL
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: NATS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: {{ .Values.api.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.api.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.api.probes.liveness.failureThreshold }}
            successThreshold: {{ .Values.api.probes.liveness.successThreshold }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.api.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.api.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.api.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.api.probes.readiness.successThreshold }}
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.api.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.api.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.api.probes.startup.failureThreshold }}
            successThreshold: {{ .Values.api.probes.startup.successThreshold }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepstack.fullname" . }}-api
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-api
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "keepstack.fullname" . }}-api
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "keepstack.fullname" . }}-api
  minReplicas: {{ .Values.api.replicas }}
  maxReplicas: {{ mul .Values.api.replicas 3 | int }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
