{{- $registry := .Values.image.registry -}}
{{- $repository := default .Values.image.apiRepository .Values.verifySchema.image.repository -}}
{{- $tag := default .Values.image.tag .Values.verifySchema.image.tag -}}
{{- $pullPolicy := default .Values.image.pullPolicy .Values.verifySchema.image.pullPolicy -}}
{{- $wait := default (dict) .Values.verifySchema.waitForDatabase -}}
{{- $waitEnabled := default true $wait.enabled -}}
{{- $waitImage := default "postgres:15.6-alpine" $wait.image -}}
{{- $waitImagePullPolicy := default "IfNotPresent" $wait.imagePullPolicy -}}
{{- $waitPoll := default 2 $wait.pollIntervalSeconds -}}
{{- $waitTimeout := default 0 $wait.timeoutSeconds -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keepstack.verifySchema.fullname" . }}
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: verify-schema
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  backoffLimit: {{ default 0 .Values.verifySchema.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "keepstack.labels" . | nindent 8 }}
        app.kubernetes.io/component: verify-schema
    spec:
      serviceAccountName: {{ include "keepstack.serviceAccountName.migrator" . }}
{{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
{{- end }}
      restartPolicy: Never
{{- if $waitEnabled }}
      initContainers:
        - name: wait-for-database
          image: {{ $waitImage }}
          imagePullPolicy: {{ $waitImagePullPolicy }}
{{- if .Values.secrets.name }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
{{- end }}
{{- if .Values.secrets.data }}
          env:
{{- range $key, $value := .Values.secrets.data }}
            - name: {{ $key }}
              value: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
{{- if gt (int $waitTimeout) 0 }}
          command:
            - sh
            - -c
            - |
              end=$((SECONDS + {{ $waitTimeout }}))
              until pg_isready -d "$DATABASE_URL"; do
                if [ $SECONDS -ge $end ]; then
                  echo "Timed out waiting for database after {{ $waitTimeout }} seconds"
                  exit 1
                fi
                echo "Waiting for database..."
                sleep {{ $waitPoll }}
              done
{{- else }}
          command:
            - sh
            - -c
            - |
              until pg_isready -d "$DATABASE_URL"; do
                echo "Waiting for database..."
                sleep {{ $waitPoll }}
              done
{{- end }}
{{- end }}
      containers:
        - name: verify-schema
          image: {{ printf "%s/%s:%s" $registry $repository $tag }}
          imagePullPolicy: {{ $pullPolicy }}
{{- if .Values.secrets.name }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
{{- end }}
{{- if .Values.secrets.data }}
          env:
{{- range $key, $value := .Values.secrets.data }}
            - name: {{ $key }}
              value: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
{{- with .Values.verifySchema.command }}
          command:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.verifySchema.args }}
          args:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.verifySchema.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
