{{- $registry := .Values.image.registry -}}
{{- $repository := default .Values.image.apiRepository .Values.verifySchema.image.repository -}}
{{- $tag := default .Values.image.tag .Values.verifySchema.image.tag -}}
{{- $pullPolicy := default .Values.image.pullPolicy .Values.verifySchema.image.pullPolicy -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keepstack.verifySchema.fullname" . }}
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: verify-schema
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  backoffLimit: {{ default 0 .Values.verifySchema.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "keepstack.labels" . | nindent 8 }}
        app.kubernetes.io/component: verify-schema
    spec:
      serviceAccountName: {{ include "keepstack.serviceAccountName.migrator" . }}
{{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
{{- end }}
      restartPolicy: Never
      containers:
        - name: verify-schema
          image: {{ printf "%s/%s:%s" $registry $repository $tag }}
          imagePullPolicy: {{ $pullPolicy }}
{{- if .Values.secrets.name }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
{{- end }}
{{- if .Values.secrets.data }}
          env:
{{- range $key, $value := .Values.secrets.data }}
            - name: {{ $key }}
              value: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
{{- with .Values.verifySchema.command }}
          command:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.verifySchema.args }}
          args:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.verifySchema.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
