{{- $registry := .Values.image.registry -}}
{{- $repository := default .Values.image.apiRepository .Values.migrate.image.repository -}}
{{- $tag := default .Values.image.tag .Values.migrate.image.tag -}}
{{- $pullPolicy := default .Values.image.pullPolicy .Values.migrate.image.pullPolicy -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keepstack.migrate.fullname" . }}
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "keepstack.labels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      serviceAccountName: {{ include "keepstack.serviceAccountName.migrator" . }}
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ printf "%s/%s:%s" $registry $repository $tag }}
          imagePullPolicy: {{ $pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
{{- with .Values.migrate.command }}
          command:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.migrate.args }}
          args:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.migrate.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
