{{- if .Values.observability.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keepstack.fullname" . }}-grafana-dashboard
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keepstack.fullname" . }}-grafana-dashboard
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
subjects:
  - kind: ServiceAccount
    name: {{ .Values.observability.grafana.serviceAccount }}
    namespace: {{ .Values.observability.grafana.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "keepstack.fullname" . }}-grafana-dashboard
{{- end }}
