apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "keepstack.fullname" . }}-nats
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  serviceName: {{ include "keepstack.fullname" . }}-nats
  replicas: {{ .Values.nats.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-nats
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-nats
        app.kubernetes.io/component: nats
    spec:
      containers:
        - name: nats
          image: {{ .Values.nats.image }}
          imagePullPolicy: IfNotPresent
          args: ["-js"]
          ports:
            - name: client
              containerPort: 4222
            - name: cluster
              containerPort: 6222
            - name: monitor
              containerPort: 8222
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepstack.fullname" . }}-nats
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-nats
  ports:
    - name: client
      port: 4222
      targetPort: client
    - name: monitor
      port: 8222
      targetPort: monitor
