apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "keepstack.fullname" . }}-postgres
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "keepstack.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-postgres
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ .Values.postgres.secretName }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  PGPASSWORD="$POSTGRES_PASSWORD" \
                    pg_isready \
                      -U "$POSTGRES_USER" \
                      -d "$POSTGRES_DB"
            initialDelaySeconds: 10
            periodSeconds: 15
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepstack.fullname" . }}-postgres
  namespace: {{ include "keepstack.namespace" . }}
  labels:
    {{- include "keepstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "keepstack.fullname" . }}-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
