{{- if .Values.tls.enabled }}
{{- if eq .Values.tls.issuer "selfsigned" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "keepstack.fullname" . }}-selfsigned
spec:
  selfSigned: {}
{{- else if or (eq .Values.tls.issuer "letsencrypt") (eq .Values.tls.issuer "letsencrypt-staging") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "keepstack.fullname" . }}-{{ .Values.tls.issuer }}
spec:
  acme:
    email: {{ .Values.tls.email | quote }}
    server: {{ if eq .Values.tls.issuer "letsencrypt" }}https://acme-v02.api.letsencrypt.org/directory{{ else }}https://acme-staging-v02.api.letsencrypt.org/directory{{ end }}
    privateKeySecretRef:
      name: {{ include "keepstack.fullname" . }}-{{ .Values.tls.issuer }}-key
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className | default "nginx" }}
{{- end }}
{{- end }}
