name: CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  REGISTRY: ghcr.io/${{ toLower(github.repository_owner) }}
  TAG: sha-${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run API tests
        run: go test ./...
        working-directory: apps/api

      - name: Run worker tests
        run: go test ./...
        working-directory: apps/worker

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install web dependencies
        run: npm ci
        working-directory: apps/web

      - name: Build web assets
        run: npm run build
        working-directory: apps/web

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/keepstack-api:${{ env.TAG }}
          platforms: linux/amd64

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/worker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/keepstack-worker:${{ env.TAG }}
          platforms: linux/amd64

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/keepstack-web:${{ env.TAG }}
          platforms: linux/amd64

      - name: Helm lint
        run: helm lint deploy/charts/keepstack
